ascii_art = """
  _  _  _        _              
 | || |(_) __ _ | |_   ___  _ _ 
 | __ || |/ _` || ' \ / -_)| '_|
 |_||_||_|\__, ||_||_|\___||_|  
  _       |___/                 
 | |    ___ __ __ __ ___  _ _   
 | |__ / _ \\ V  V // -_)| '_|  
 |____|\___/ \_/\_/ \___||_|    
                                  
"""

people = [
    {"name": "Cristiano Ronaldo", "description": "Footballer, Forward", "followers": 580_000_000, "country": "Portugal"},
    {"name": "Lionel Messi", "description": "Footballer, Forward", "followers": 400_000_000, "country": "Argentina"},
    {"name": "Kylie Jenner", "description": "Entrepreneur, Reality TV Star", "followers": 380_000_000, "country": "USA"},
    {"name": "Dwayne Johnson", "description": "Actor, Former Wrestler", "followers": 355_000_000, "country": "USA"},
    {"name": "Selena Gomez", "description": "Singer, Actress", "followers": 350_000_000, "country": "USA"},
    {"name": "Ariana Grande", "description": "Singer, Actress", "followers": 330_000_000, "country": "USA"},
    {"name": "Kim Kardashian", "description": "Reality TV Star, Entrepreneur", "followers": 320_000_000, "country": "USA"},
    {"name": "Beyoncé", "description": "Singer, Actress", "followers": 270_000_000, "country": "USA"},
    {"name": "Justin Bieber", "description": "Singer", "followers": 260_000_000, "country": "Canada"},
    {"name": "Nicki Minaj", "description": "Rapper, Singer", "followers": 220_000_000, "country": "Trinidad and Tobago"},
    {"name": "Taylor Swift", "description": "Singer, Songwriter", "followers": 210_000_000, "country": "USA"},
    {"name": "Kendall Jenner", "description": "Model, Reality TV Star", "followers": 200_000_000, "country": "USA"},
    {"name": "Kevin Hart", "description": "Comedian, Actor", "followers": 180_000_000, "country": "USA"},
    {"name": "Zendaya", "description": "Actress, Singer", "followers": 175_000_000, "country": "USA"},
    {"name": "Billie Eilish", "description": "Singer, Songwriter", "followers": 170_000_000, "country": "USA"},
    {"name": "Will Smith", "description": "Actor, Rapper", "followers": 160_000_000, "country": "USA"},
    {"name": "Shakira", "description": "Singer, Dancer", "followers": 150_000_000, "country": "Colombia"},
    {"name": "David Beckham", "description": "Footballer, Model", "followers": 145_000_000, "country": "UK"},
    {"name": "Miley Cyrus", "description": "Singer, Actress", "followers": 140_000_000, "country": "USA"},
    {"name": "Kourtney Kardashian", "description": "Reality TV Star, Entrepreneur", "followers": 135_000_000, "country": "USA"},
    {"name": "Gigi Hadid", "description": "Model", "followers": 130_000_000, "country": "USA"},
    {"name": "Virat Kohli", "description": "Cricketer", "followers": 125_000_000, "country": "India"},
    {"name": "Chris Brown", "description": "Singer, Dancer", "followers": 120_000_000, "country": "USA"},
    {"name": "Emma Watson", "description": "Actress, Activist", "followers": 115_000_000, "country": "UK"},
    {"name": "Cardi B", "description": "Rapper", "followers": 110_000_000, "country": "USA"},
    {"name": "Neymar Jr", "description": "Footballer", "followers": 105_000_000, "country": "Brazil"},
    {"name": "Dua Lipa", "description": "Singer", "followers": 100_000_000, "country": "UK"},
    {"name": "Gal Gadot", "description": "Actress, Model", "followers": 95_000_000, "country": "Israel"},
    {"name": "Ellen DeGeneres", "description": "TV Host, Comedian", "followers": 90_000_000, "country": "USA"},
    {"name": "Drake", "description": "Rapper, Singer", "followers": 88_000_000, "country": "Canada"},
    {"name": "Kylie Jenner", "description": "Beauty Mogul, TV Star", "followers": 380_000_000, "country": "USA"},
    {"name": "Zendaya", "description": "Actress", "followers": 175_000_000, "country": "USA"},
    {"name": "Shawn Mendes", "description": "Singer, Songwriter", "followers": 85_000_000, "country": "Canada"},
    {"name": "Huda Kattan", "description": "Beauty Influencer, Entrepreneur", "followers": 80_000_000, "country": "USA"},
    {"name": "BTS (group)", "description": "K-Pop Band", "followers": 75_000_000, "country": "South Korea"},
    {"name": "Priyanka Chopra", "description": "Actress, Singer", "followers": 70_000_000, "country": "India"},
    {"name": "Eiza González", "description": "Actress, Singer", "followers": 68_000_000, "country": "Mexico"},
    {"name": "Kevin Hart", "description": "Comedian, Actor", "followers": 180_000_000, "country": "USA"},
    {"name": "Jennifer Lopez", "description": "Singer, Actress", "followers": 67_000_000, "country": "USA"},
    {"name": "Cara Delevingne", "description": "Model, Actress", "followers": 65_000_000, "country": "UK"},
    {"name": "Snoop Dogg", "description": "Rapper, Actor", "followers": 62_000_000, "country": "USA"},
    {"name": "Serena Williams", "description": "Tennis Player", "followers": 60_000_000, "country": "USA"},
    {"name": "Michelle Obama", "description": "Former First Lady", "followers": 58_000_000, "country": "USA"},
    {"name": "Maluma", "description": "Singer", "followers": 57_000_000, "country": "Colombia"},
    {"name": "Mark Wahlberg", "description": "Actor", "followers": 55_000_000, "country": "USA"},
    {"name": "Bruno Mars", "description": "Singer, Songwriter", "followers": 53_000_000, "country": "USA"},
    {"name": "Megan Fox", "description": "Actress", "followers": 52_000_000, "country": "USA"},
    {"name": "J Balvin", "description": "Singer", "followers": 50_000_000, "country": "Colombia"},
    {"name": "Gal Gadot", "description": "Actress, Model", "followers": 95_000_000, "country": "Israel"},
    {"name": "Chris Hemsworth", "description": "Actor", "followers": 49_000_000, "country": "Australia"},
    {"name": "Lilly Singh", "description": "YouTuber, Comedian", "followers": 48_000_000, "country": "Canada"},
    {"name": "Billie Eilish", "description": "Singer, Songwriter", "followers": 170_000_000, "country": "USA"},
    {"name": "Natalie Portman", "description": "Actress", "followers": 46_000_000, "country": "USA"},
    {"name": "Amy Schumer", "description": "Comedian, Actress", "followers": 44_000_000, "country": "USA"},
    {"name": "Sofia Vergara", "description": "Actress, Model", "followers": 43_000_000, "country": "Colombia"},
    {"name": "Adele", "description": "Singer, Songwriter", "followers": 41_000_000, "country": "UK"},
    {"name": "Rihanna", "description": "Singer, Entrepreneur", "followers": 125_000_000, "country": "Barbados"},
    {"name": "Ed Sheeran", "description": "Singer, Songwriter", "followers": 39_000_000, "country": "UK"},
    {"name": "LeBron James", "description": "Basketball Player", "followers": 115_000_000, "country": "USA"},
    {"name": "J.Lo", "description": "Singer, Actress", "followers": 145_000_000, "country": "USA"},
    {"name": "Zendaya", "description": "Actress, Singer", "followers": 175_000_000, "country": "USA"},
    {"name": "Kourtney Kardashian", "description": "TV Personality", "followers": 135_000_000, "country": "USA"},
    {"name": "Bella Hadid", "description": "Model", "followers": 40_000_000, "country": "USA"},
    {"name": "Shawn Mendes", "description": "Singer, Songwriter", "followers": 85_000_000, "country": "Canada"},
    {"name": "Megan Thee Stallion", "description": "Rapper", "followers": 42_000_000, "country": "USA"},
    {"name": "Bad Bunny", "description": "Singer", "followers": 47_000_000, "country": "Puerto Rico"},
    {"name": "Camila Cabello", "description": "Singer", "followers": 83_000_000, "country": "USA"},
    {"name": "Zayn Malik", "description": "Singer", "followers": 45_000_000, "country": "UK"},
    {"name": "Selena Gomez", "description": "Singer, Actress", "followers": 350_000_000, "country": "USA"},
    {"name": "Kendall Jenner", "description": "Model, TV Personality", "followers": 200_000_000, "country": "USA"},
    {"name": "Paris Hilton", "description": "Socialite, TV Personality", "followers": 20_000_000, "country": "USA"},
    {"name": "Neymar Jr", "description": "Footballer", "followers": 105_000_000, "country": "Brazil"},
    {"name": "Post Malone", "description": "Singer, Rapper", "followers": 28_000_000, "country": "USA"},
    {"name": "Kourtney Kardashian", "description": "Reality TV Star", "followers": 135_000_000, "country": "USA"},
    {"name": "Gwen Stefani", "description": "Singer", "followers": 22_000_000, "country": "USA"},
    {"name": "Tyler, The Creator", "description": "Rapper, Producer", "followers": 15_000_000, "country": "USA"},
    {"name": "Adele", "description": "Singer", "followers": 41_000_000, "country": "UK"},
    {"name": "Cardi B", "description": "Rapper", "followers": 110_000_000, "country": "USA"},
    {"name": "Lea Michele", "description": "Actress, Singer", "followers": 19_000_000, "country": "USA"},
    {"name": "Lizzo", "description": "Singer, Rapper", "followers": 13_000_000, "country": "USA"},
    {"name": "Tom Holland", "description": "Actor", "followers": 55_000_000, "country": "UK"},
    {"name": "Margot Robbie", "description": "Actress", "followers": 25_000_000, "country": "Australia"},
    {"name": "Emma Stone", "description": "Actress", "followers": 20_000_000, "country": "USA"},
    {"name": "Chris Evans", "description": "Actor", "followers": 30_000_000, "country": "USA"},
    {"name": "Gal Gadot", "description": "Actress", "followers": 95_000_000, "country": "Israel"},
]

